# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import validator_change_pb2 as validator__change__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='consensus.proto',
  package='consensus',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x63onsensus.proto\x12\tconsensus\x1a\x16validator_change.proto\"\xdf\x02\n\x0c\x43onsensusMsg\x12\'\n\x08proposal\x18\x01 \x01(\x0b\x32\x13.consensus.ProposalH\x00\x12&\n\x08vote_msg\x18\x02 \x01(\x0b\x32\x12.consensus.VoteMsgH\x00\x12\x30\n\rrequest_block\x18\x03 \x01(\x0b\x32\x17.consensus.RequestBlockH\x00\x12\x30\n\rrespond_block\x18\x04 \x01(\x0b\x32\x17.consensus.RespondBlockH\x00\x12(\n\tsync_info\x18\x05 \x01(\x0b\x32\x13.consensus.SyncInfoH\x00\x12\x33\n\x0c\x65poch_change\x18\x06 \x01(\x0b\x32\x1b.types.ValidatorChangeProofH\x00\x12\x30\n\rrequest_epoch\x18\x07 \x01(\x0b\x32\x17.consensus.RequestEpochH\x00\x42\t\n\x07message\"\x19\n\x08Proposal\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\"\x19\n\x08SyncInfo\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\"\x16\n\x05\x42lock\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\"\x18\n\x07VoteMsg\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\"\x1d\n\x0cVoteProposal\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\"\x1d\n\x0cRequestBlock\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\"\x1d\n\x0cRespondBlock\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\"\x1d\n\x0cRequestEpoch\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\x62\x06proto3')
  ,
  dependencies=[validator__change__pb2.DESCRIPTOR,])




_CONSENSUSMSG = _descriptor.Descriptor(
  name='ConsensusMsg',
  full_name='consensus.ConsensusMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposal', full_name='consensus.ConsensusMsg.proposal', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vote_msg', full_name='consensus.ConsensusMsg.vote_msg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_block', full_name='consensus.ConsensusMsg.request_block', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='respond_block', full_name='consensus.ConsensusMsg.respond_block', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sync_info', full_name='consensus.ConsensusMsg.sync_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_change', full_name='consensus.ConsensusMsg.epoch_change', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_epoch', full_name='consensus.ConsensusMsg.request_epoch', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='consensus.ConsensusMsg.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=55,
  serialized_end=406,
)


_PROPOSAL = _descriptor.Descriptor(
  name='Proposal',
  full_name='consensus.Proposal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='consensus.Proposal.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=433,
)


_SYNCINFO = _descriptor.Descriptor(
  name='SyncInfo',
  full_name='consensus.SyncInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='consensus.SyncInfo.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=460,
)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='consensus.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='consensus.Block.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=484,
)


_VOTEMSG = _descriptor.Descriptor(
  name='VoteMsg',
  full_name='consensus.VoteMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='consensus.VoteMsg.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=510,
)


_VOTEPROPOSAL = _descriptor.Descriptor(
  name='VoteProposal',
  full_name='consensus.VoteProposal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='consensus.VoteProposal.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=541,
)


_REQUESTBLOCK = _descriptor.Descriptor(
  name='RequestBlock',
  full_name='consensus.RequestBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='consensus.RequestBlock.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=572,
)


_RESPONDBLOCK = _descriptor.Descriptor(
  name='RespondBlock',
  full_name='consensus.RespondBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='consensus.RespondBlock.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=603,
)


_REQUESTEPOCH = _descriptor.Descriptor(
  name='RequestEpoch',
  full_name='consensus.RequestEpoch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='consensus.RequestEpoch.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=634,
)

_CONSENSUSMSG.fields_by_name['proposal'].message_type = _PROPOSAL
_CONSENSUSMSG.fields_by_name['vote_msg'].message_type = _VOTEMSG
_CONSENSUSMSG.fields_by_name['request_block'].message_type = _REQUESTBLOCK
_CONSENSUSMSG.fields_by_name['respond_block'].message_type = _RESPONDBLOCK
_CONSENSUSMSG.fields_by_name['sync_info'].message_type = _SYNCINFO
_CONSENSUSMSG.fields_by_name['epoch_change'].message_type = validator__change__pb2._VALIDATORCHANGEPROOF
_CONSENSUSMSG.fields_by_name['request_epoch'].message_type = _REQUESTEPOCH
_CONSENSUSMSG.oneofs_by_name['message'].fields.append(
  _CONSENSUSMSG.fields_by_name['proposal'])
_CONSENSUSMSG.fields_by_name['proposal'].containing_oneof = _CONSENSUSMSG.oneofs_by_name['message']
_CONSENSUSMSG.oneofs_by_name['message'].fields.append(
  _CONSENSUSMSG.fields_by_name['vote_msg'])
_CONSENSUSMSG.fields_by_name['vote_msg'].containing_oneof = _CONSENSUSMSG.oneofs_by_name['message']
_CONSENSUSMSG.oneofs_by_name['message'].fields.append(
  _CONSENSUSMSG.fields_by_name['request_block'])
_CONSENSUSMSG.fields_by_name['request_block'].containing_oneof = _CONSENSUSMSG.oneofs_by_name['message']
_CONSENSUSMSG.oneofs_by_name['message'].fields.append(
  _CONSENSUSMSG.fields_by_name['respond_block'])
_CONSENSUSMSG.fields_by_name['respond_block'].containing_oneof = _CONSENSUSMSG.oneofs_by_name['message']
_CONSENSUSMSG.oneofs_by_name['message'].fields.append(
  _CONSENSUSMSG.fields_by_name['sync_info'])
_CONSENSUSMSG.fields_by_name['sync_info'].containing_oneof = _CONSENSUSMSG.oneofs_by_name['message']
_CONSENSUSMSG.oneofs_by_name['message'].fields.append(
  _CONSENSUSMSG.fields_by_name['epoch_change'])
_CONSENSUSMSG.fields_by_name['epoch_change'].containing_oneof = _CONSENSUSMSG.oneofs_by_name['message']
_CONSENSUSMSG.oneofs_by_name['message'].fields.append(
  _CONSENSUSMSG.fields_by_name['request_epoch'])
_CONSENSUSMSG.fields_by_name['request_epoch'].containing_oneof = _CONSENSUSMSG.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['ConsensusMsg'] = _CONSENSUSMSG
DESCRIPTOR.message_types_by_name['Proposal'] = _PROPOSAL
DESCRIPTOR.message_types_by_name['SyncInfo'] = _SYNCINFO
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['VoteMsg'] = _VOTEMSG
DESCRIPTOR.message_types_by_name['VoteProposal'] = _VOTEPROPOSAL
DESCRIPTOR.message_types_by_name['RequestBlock'] = _REQUESTBLOCK
DESCRIPTOR.message_types_by_name['RespondBlock'] = _RESPONDBLOCK
DESCRIPTOR.message_types_by_name['RequestEpoch'] = _REQUESTEPOCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConsensusMsg = _reflection.GeneratedProtocolMessageType('ConsensusMsg', (_message.Message,), {
  'DESCRIPTOR' : _CONSENSUSMSG,
  '__module__' : 'consensus_pb2'
  # @@protoc_insertion_point(class_scope:consensus.ConsensusMsg)
  })
_sym_db.RegisterMessage(ConsensusMsg)

Proposal = _reflection.GeneratedProtocolMessageType('Proposal', (_message.Message,), {
  'DESCRIPTOR' : _PROPOSAL,
  '__module__' : 'consensus_pb2'
  # @@protoc_insertion_point(class_scope:consensus.Proposal)
  })
_sym_db.RegisterMessage(Proposal)

SyncInfo = _reflection.GeneratedProtocolMessageType('SyncInfo', (_message.Message,), {
  'DESCRIPTOR' : _SYNCINFO,
  '__module__' : 'consensus_pb2'
  # @@protoc_insertion_point(class_scope:consensus.SyncInfo)
  })
_sym_db.RegisterMessage(SyncInfo)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'consensus_pb2'
  # @@protoc_insertion_point(class_scope:consensus.Block)
  })
_sym_db.RegisterMessage(Block)

VoteMsg = _reflection.GeneratedProtocolMessageType('VoteMsg', (_message.Message,), {
  'DESCRIPTOR' : _VOTEMSG,
  '__module__' : 'consensus_pb2'
  # @@protoc_insertion_point(class_scope:consensus.VoteMsg)
  })
_sym_db.RegisterMessage(VoteMsg)

VoteProposal = _reflection.GeneratedProtocolMessageType('VoteProposal', (_message.Message,), {
  'DESCRIPTOR' : _VOTEPROPOSAL,
  '__module__' : 'consensus_pb2'
  # @@protoc_insertion_point(class_scope:consensus.VoteProposal)
  })
_sym_db.RegisterMessage(VoteProposal)

RequestBlock = _reflection.GeneratedProtocolMessageType('RequestBlock', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTBLOCK,
  '__module__' : 'consensus_pb2'
  # @@protoc_insertion_point(class_scope:consensus.RequestBlock)
  })
_sym_db.RegisterMessage(RequestBlock)

RespondBlock = _reflection.GeneratedProtocolMessageType('RespondBlock', (_message.Message,), {
  'DESCRIPTOR' : _RESPONDBLOCK,
  '__module__' : 'consensus_pb2'
  # @@protoc_insertion_point(class_scope:consensus.RespondBlock)
  })
_sym_db.RegisterMessage(RespondBlock)

RequestEpoch = _reflection.GeneratedProtocolMessageType('RequestEpoch', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTEPOCH,
  '__module__' : 'consensus_pb2'
  # @@protoc_insertion_point(class_scope:consensus.RequestEpoch)
  })
_sym_db.RegisterMessage(RequestEpoch)


# @@protoc_insertion_point(module_scope)
