# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mempool.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import transaction_pb2 as transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mempool.proto',
  package='network',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmempool.proto\x12\x07network\x1a\x11transaction.proto\"Q\n\x0eMempoolSyncMsg\x12\x0f\n\x07peer_id\x18\x01 \x01(\x0c\x12.\n\x0ctransactions\x18\x02 \x03(\x0b\x32\x18.types.SignedTransactionb\x06proto3')
  ,
  dependencies=[transaction__pb2.DESCRIPTOR,])




_MEMPOOLSYNCMSG = _descriptor.Descriptor(
  name='MempoolSyncMsg',
  full_name='network.MempoolSyncMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peer_id', full_name='network.MempoolSyncMsg.peer_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactions', full_name='network.MempoolSyncMsg.transactions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=126,
)

_MEMPOOLSYNCMSG.fields_by_name['transactions'].message_type = transaction__pb2._SIGNEDTRANSACTION
DESCRIPTOR.message_types_by_name['MempoolSyncMsg'] = _MEMPOOLSYNCMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MempoolSyncMsg = _reflection.GeneratedProtocolMessageType('MempoolSyncMsg', (_message.Message,), {
  'DESCRIPTOR' : _MEMPOOLSYNCMSG,
  '__module__' : 'mempool_pb2'
  # @@protoc_insertion_point(class_scope:network.MempoolSyncMsg)
  })
_sym_db.RegisterMessage(MempoolSyncMsg)


# @@protoc_insertion_point(module_scope)
