# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='network.proto',
  package='network',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rnetwork.proto\x12\x07network\"(\n\x08PeerInfo\x12\r\n\x05\x65poch\x18\x01 \x01(\x04\x12\r\n\x05\x61\x64\x64rs\x18\x02 \x03(\x0c\"6\n\x0eSignedPeerInfo\x12\x11\n\tpeer_info\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"7\n\x0f\x46ullNodePayload\x12\r\n\x05\x65poch\x18\x01 \x01(\x04\x12\x15\n\rdns_seed_addr\x18\x02 \x01(\x0c\";\n\x15SignedFullNodePayload\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"\x8c\x01\n\x04Note\x12\x0f\n\x07peer_id\x18\x01 \x01(\x0c\x12\x31\n\x10signed_peer_info\x18\x02 \x01(\x0b\x32\x17.network.SignedPeerInfo\x12@\n\x18signed_full_node_payload\x18\x03 \x01(\x0b\x32\x1e.network.SignedFullNodePayload\",\n\x0c\x44iscoveryMsg\x12\x1c\n\x05notes\x18\x01 \x03(\x0b\x32\r.network.Note\"\x8a\x01\n\x0bIdentityMsg\x12\x0f\n\x07peer_id\x18\x01 \x01(\x0c\x12\x1b\n\x13supported_protocols\x18\x02 \x03(\x0c\x12\'\n\x04role\x18\x03 \x01(\x0e\x32\x19.network.IdentityMsg.Role\"$\n\x04Role\x12\r\n\tVALIDATOR\x10\x00\x12\r\n\tFULL_NODE\x10\x01\x62\x06proto3')
)



_IDENTITYMSG_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='network.IdentityMsg.Role',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VALIDATOR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FULL_NODE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=534,
  serialized_end=570,
)
_sym_db.RegisterEnumDescriptor(_IDENTITYMSG_ROLE)


_PEERINFO = _descriptor.Descriptor(
  name='PeerInfo',
  full_name='network.PeerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='epoch', full_name='network.PeerInfo.epoch', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addrs', full_name='network.PeerInfo.addrs', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=66,
)


_SIGNEDPEERINFO = _descriptor.Descriptor(
  name='SignedPeerInfo',
  full_name='network.SignedPeerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peer_info', full_name='network.SignedPeerInfo.peer_info', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='network.SignedPeerInfo.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=122,
)


_FULLNODEPAYLOAD = _descriptor.Descriptor(
  name='FullNodePayload',
  full_name='network.FullNodePayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='epoch', full_name='network.FullNodePayload.epoch', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dns_seed_addr', full_name='network.FullNodePayload.dns_seed_addr', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=179,
)


_SIGNEDFULLNODEPAYLOAD = _descriptor.Descriptor(
  name='SignedFullNodePayload',
  full_name='network.SignedFullNodePayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='network.SignedFullNodePayload.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='network.SignedFullNodePayload.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=240,
)


_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='network.Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peer_id', full_name='network.Note.peer_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signed_peer_info', full_name='network.Note.signed_peer_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signed_full_node_payload', full_name='network.Note.signed_full_node_payload', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=383,
)


_DISCOVERYMSG = _descriptor.Descriptor(
  name='DiscoveryMsg',
  full_name='network.DiscoveryMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notes', full_name='network.DiscoveryMsg.notes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=429,
)


_IDENTITYMSG = _descriptor.Descriptor(
  name='IdentityMsg',
  full_name='network.IdentityMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peer_id', full_name='network.IdentityMsg.peer_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supported_protocols', full_name='network.IdentityMsg.supported_protocols', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='network.IdentityMsg.role', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IDENTITYMSG_ROLE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=570,
)

_NOTE.fields_by_name['signed_peer_info'].message_type = _SIGNEDPEERINFO
_NOTE.fields_by_name['signed_full_node_payload'].message_type = _SIGNEDFULLNODEPAYLOAD
_DISCOVERYMSG.fields_by_name['notes'].message_type = _NOTE
_IDENTITYMSG.fields_by_name['role'].enum_type = _IDENTITYMSG_ROLE
_IDENTITYMSG_ROLE.containing_type = _IDENTITYMSG
DESCRIPTOR.message_types_by_name['PeerInfo'] = _PEERINFO
DESCRIPTOR.message_types_by_name['SignedPeerInfo'] = _SIGNEDPEERINFO
DESCRIPTOR.message_types_by_name['FullNodePayload'] = _FULLNODEPAYLOAD
DESCRIPTOR.message_types_by_name['SignedFullNodePayload'] = _SIGNEDFULLNODEPAYLOAD
DESCRIPTOR.message_types_by_name['Note'] = _NOTE
DESCRIPTOR.message_types_by_name['DiscoveryMsg'] = _DISCOVERYMSG
DESCRIPTOR.message_types_by_name['IdentityMsg'] = _IDENTITYMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PeerInfo = _reflection.GeneratedProtocolMessageType('PeerInfo', (_message.Message,), {
  'DESCRIPTOR' : _PEERINFO,
  '__module__' : 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.PeerInfo)
  })
_sym_db.RegisterMessage(PeerInfo)

SignedPeerInfo = _reflection.GeneratedProtocolMessageType('SignedPeerInfo', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDPEERINFO,
  '__module__' : 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.SignedPeerInfo)
  })
_sym_db.RegisterMessage(SignedPeerInfo)

FullNodePayload = _reflection.GeneratedProtocolMessageType('FullNodePayload', (_message.Message,), {
  'DESCRIPTOR' : _FULLNODEPAYLOAD,
  '__module__' : 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.FullNodePayload)
  })
_sym_db.RegisterMessage(FullNodePayload)

SignedFullNodePayload = _reflection.GeneratedProtocolMessageType('SignedFullNodePayload', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDFULLNODEPAYLOAD,
  '__module__' : 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.SignedFullNodePayload)
  })
_sym_db.RegisterMessage(SignedFullNodePayload)

Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), {
  'DESCRIPTOR' : _NOTE,
  '__module__' : 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.Note)
  })
_sym_db.RegisterMessage(Note)

DiscoveryMsg = _reflection.GeneratedProtocolMessageType('DiscoveryMsg', (_message.Message,), {
  'DESCRIPTOR' : _DISCOVERYMSG,
  '__module__' : 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.DiscoveryMsg)
  })
_sym_db.RegisterMessage(DiscoveryMsg)

IdentityMsg = _reflection.GeneratedProtocolMessageType('IdentityMsg', (_message.Message,), {
  'DESCRIPTOR' : _IDENTITYMSG,
  '__module__' : 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.IdentityMsg)
  })
_sym_db.RegisterMessage(IdentityMsg)


# @@protoc_insertion_point(module_scope)
