# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secret_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='secret_service.proto',
  package='secret_service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14secret_service.proto\x12\x0esecret_service\";\n\x12GenerateKeyRequest\x12%\n\x04spec\x18\x01 \x01(\x0e\x32\x17.secret_service.KeyType\"N\n\x13GenerateKeyResponse\x12\x0e\n\x06key_id\x18\x01 \x01(\x0c\x12\'\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x19.secret_service.ErrorCode\"\"\n\x10PublicKeyRequest\x12\x0e\n\x06key_id\x18\x01 \x01(\x0c\"P\n\x11PublicKeyResponse\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12\'\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x19.secret_service.ErrorCode\"3\n\x0bSignRequest\x12\x0e\n\x06key_id\x18\x01 \x01(\x0c\x12\x14\n\x0cmessage_hash\x18\x02 \x01(\x0c\"J\n\x0cSignResponse\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x12\'\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x19.secret_service.ErrorCode*~\n\tErrorCode\x12\x0b\n\x07Success\x10\x00\x12\x11\n\rKeyIdNotFound\x10\x01\x12\x0f\n\x0bWrongLength\x10\x02\x12\x15\n\x11InvalidParameters\x10\x03\x12\x18\n\x14\x41uthenticationFailed\x10\x04\x12\x0f\n\x0bUnspecified\x10\x05*$\n\x07KeyType\x12\x0b\n\x07\x45\x64\x32\x35\x35\x31\x39\x10\x00\x12\x0c\n\x08\x42LS12381\x10\x01\x32\x85\x02\n\rSecretService\x12X\n\x0bGenerateKey\x12\".secret_service.GenerateKeyRequest\x1a#.secret_service.GenerateKeyResponse\"\x00\x12U\n\x0cGetPublicKey\x12 .secret_service.PublicKeyRequest\x1a!.secret_service.PublicKeyResponse\"\x00\x12\x43\n\x04Sign\x12\x1b.secret_service.SignRequest\x1a\x1c.secret_service.SignResponse\"\x00\x62\x06proto3')
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='secret_service.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Success', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KeyIdNotFound', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WrongLength', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidParameters', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AuthenticationFailed', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Unspecified', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=428,
  serialized_end=554,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
_KEYTYPE = _descriptor.EnumDescriptor(
  name='KeyType',
  full_name='secret_service.KeyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ed25519', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLS12381', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=556,
  serialized_end=592,
)
_sym_db.RegisterEnumDescriptor(_KEYTYPE)

KeyType = enum_type_wrapper.EnumTypeWrapper(_KEYTYPE)
Success = 0
KeyIdNotFound = 1
WrongLength = 2
InvalidParameters = 3
AuthenticationFailed = 4
Unspecified = 5
Ed25519 = 0
BLS12381 = 1



_GENERATEKEYREQUEST = _descriptor.Descriptor(
  name='GenerateKeyRequest',
  full_name='secret_service.GenerateKeyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spec', full_name='secret_service.GenerateKeyRequest.spec', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=99,
)


_GENERATEKEYRESPONSE = _descriptor.Descriptor(
  name='GenerateKeyResponse',
  full_name='secret_service.GenerateKeyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_id', full_name='secret_service.GenerateKeyResponse.key_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='secret_service.GenerateKeyResponse.code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=179,
)


_PUBLICKEYREQUEST = _descriptor.Descriptor(
  name='PublicKeyRequest',
  full_name='secret_service.PublicKeyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_id', full_name='secret_service.PublicKeyRequest.key_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=215,
)


_PUBLICKEYRESPONSE = _descriptor.Descriptor(
  name='PublicKeyResponse',
  full_name='secret_service.PublicKeyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='secret_service.PublicKeyResponse.public_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='secret_service.PublicKeyResponse.code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=297,
)


_SIGNREQUEST = _descriptor.Descriptor(
  name='SignRequest',
  full_name='secret_service.SignRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_id', full_name='secret_service.SignRequest.key_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_hash', full_name='secret_service.SignRequest.message_hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=350,
)


_SIGNRESPONSE = _descriptor.Descriptor(
  name='SignResponse',
  full_name='secret_service.SignResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='secret_service.SignResponse.signature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='secret_service.SignResponse.code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=426,
)

_GENERATEKEYREQUEST.fields_by_name['spec'].enum_type = _KEYTYPE
_GENERATEKEYRESPONSE.fields_by_name['code'].enum_type = _ERRORCODE
_PUBLICKEYRESPONSE.fields_by_name['code'].enum_type = _ERRORCODE
_SIGNRESPONSE.fields_by_name['code'].enum_type = _ERRORCODE
DESCRIPTOR.message_types_by_name['GenerateKeyRequest'] = _GENERATEKEYREQUEST
DESCRIPTOR.message_types_by_name['GenerateKeyResponse'] = _GENERATEKEYRESPONSE
DESCRIPTOR.message_types_by_name['PublicKeyRequest'] = _PUBLICKEYREQUEST
DESCRIPTOR.message_types_by_name['PublicKeyResponse'] = _PUBLICKEYRESPONSE
DESCRIPTOR.message_types_by_name['SignRequest'] = _SIGNREQUEST
DESCRIPTOR.message_types_by_name['SignResponse'] = _SIGNRESPONSE
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
DESCRIPTOR.enum_types_by_name['KeyType'] = _KEYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenerateKeyRequest = _reflection.GeneratedProtocolMessageType('GenerateKeyRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEKEYREQUEST,
  '__module__' : 'secret_service_pb2'
  # @@protoc_insertion_point(class_scope:secret_service.GenerateKeyRequest)
  })
_sym_db.RegisterMessage(GenerateKeyRequest)

GenerateKeyResponse = _reflection.GeneratedProtocolMessageType('GenerateKeyResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEKEYRESPONSE,
  '__module__' : 'secret_service_pb2'
  # @@protoc_insertion_point(class_scope:secret_service.GenerateKeyResponse)
  })
_sym_db.RegisterMessage(GenerateKeyResponse)

PublicKeyRequest = _reflection.GeneratedProtocolMessageType('PublicKeyRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICKEYREQUEST,
  '__module__' : 'secret_service_pb2'
  # @@protoc_insertion_point(class_scope:secret_service.PublicKeyRequest)
  })
_sym_db.RegisterMessage(PublicKeyRequest)

PublicKeyResponse = _reflection.GeneratedProtocolMessageType('PublicKeyResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICKEYRESPONSE,
  '__module__' : 'secret_service_pb2'
  # @@protoc_insertion_point(class_scope:secret_service.PublicKeyResponse)
  })
_sym_db.RegisterMessage(PublicKeyResponse)

SignRequest = _reflection.GeneratedProtocolMessageType('SignRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNREQUEST,
  '__module__' : 'secret_service_pb2'
  # @@protoc_insertion_point(class_scope:secret_service.SignRequest)
  })
_sym_db.RegisterMessage(SignRequest)

SignResponse = _reflection.GeneratedProtocolMessageType('SignResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNRESPONSE,
  '__module__' : 'secret_service_pb2'
  # @@protoc_insertion_point(class_scope:secret_service.SignResponse)
  })
_sym_db.RegisterMessage(SignResponse)



_SECRETSERVICE = _descriptor.ServiceDescriptor(
  name='SecretService',
  full_name='secret_service.SecretService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=595,
  serialized_end=856,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateKey',
    full_name='secret_service.SecretService.GenerateKey',
    index=0,
    containing_service=None,
    input_type=_GENERATEKEYREQUEST,
    output_type=_GENERATEKEYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPublicKey',
    full_name='secret_service.SecretService.GetPublicKey',
    index=1,
    containing_service=None,
    input_type=_PUBLICKEYREQUEST,
    output_type=_PUBLICKEYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Sign',
    full_name='secret_service.SecretService.Sign',
    index=2,
    containing_service=None,
    input_type=_SIGNREQUEST,
    output_type=_SIGNRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SECRETSERVICE)

DESCRIPTOR.services_by_name['SecretService'] = _SECRETSERVICE

# @@protoc_insertion_point(module_scope)
